### PR TITLE
remove s2_ard_granule from ows

### PR DESCRIPTION
**Pull request by pindge**
- s2a_ard_granule and s2b_ard_granule are deleted from dev

### CODE REVIEW

**Comment by alexgleith** [comment]
Are these definitely the THREDDS layers?

And are the S3 layers in there at all?

**Comment by pindge** [comment]
> Are these definitely the THREDDS layers?
> 
> And are the S3 layers in there at all?

these are https://explorer.dev.dea.ga.gov.au/dataset/063a9635-4445-47a2-b51d-558ccbc1b793 thredds ones.

another verification we have is this page https://explorer-reader.dea.ga.gov.au/about
```

s2b_ard_granule | 263,180 | http:/dapds00.nci.org.au/thredds/fileServer/if87
-- | -- | --


s2a_ard_granule | 343,875 | http:/dapds00.nci.org.au/thredds/fileServer/if87
-- | -- | --

```

**Comment by pindge** [comment]
```

ga_s2a_ard_nbar_granule | 254,817 | s3:/dea-public-data/L2/sentinel-2-nbar/S2MSIARD_NBAR/2020-10-08 | - | doc | eo_plus
-- | -- | -- | -- | -- | --
ga_s2b_ard_nbar_granule | 264,915 | s3:/dea-public-data/L2/sentinel-2-nbar/S2MSIARD_NBAR

```
the s3 ards are not deployed to ows yet.

**Comment by alexgleith** [comment]
Best talk to Dave about removing these before adding the others. We might want to swap them over.

**Review by GypsyBojangles — APPROVED** [review]

**Pull request merged**
