### PR TITLE
Add WPS and Band math examples

### PR DESCRIPTION
**Pull request by GypsyBojangles**
Add WPS and Band math examples to prototype group.

### CODE REVIEW

**Comment by robbibt** [comment]
I get this error when trying to add the GSKY band math layer to Terriacube:
image

**Comment by robbibt** [comment]
And this error when trying to run a Water Observations from Space Daily Pixel Drill WPS analysis (this is as a naïve user, there might be important steps I'm missing to get them to work correctly): 
image

**Comment by GypsyBojangles** [comment]
> And this error when trying to run a Water Observations from Space Daily Pixel Drill WPS analysis (this is as a naïve user, there might be important steps I'm missing to get them to work correctly):
> image

This is to do with the S3 bucket CORS policy, @mmochan  and @benjimin  are looking into this now. The WPS is functioning correctly.

**Comment by GypsyBojangles** [comment]
> I get this error when trying to add the GSKY band math layer to Terriacube:
> image

Ok, this has been fixed.

**Comment by GypsyBojangles** [comment]
To be honest, this is still a development site and I believe that flakey web services being included here for the purposes of testing is "ok" so long as they are under active development. @robbibt what do you think? Noting I have addressed one of the issues you identified, but the other is a WIP.

**Comment by robbibt** [comment]
Sounds good to me!

**Review by robbibt — APPROVED** [review]
Forgot to approve, looks good!

**Pull request merged**
