### PR TITLE
Change the product directory structure

### PR DESCRIPTION
**Pull request by alexgleith**
## Context
We have two ODC config spaces, one here in the `dea-config` repo and one in the `digitalearthau` repo.

This PR is a proposed directory structure that will combine the two config spaces, and should be considered along with [another PR](https://github.com/GeoscienceAustralia/digitalearthau/pull/271), which cleans out the config directory over in the other repo.

Basic idea is that we have this structure:
* `products/collection-2`: history. It's a mess, leave it alone
* `products/collection-3-aws`: the main source of all ODC config files. With a nice directory structure and naming conventions
* `products/collection-3-nci`: should be considered an 'overlay' directory with the previous directory. This contains differences from the previous dir, which can be merged in, making it work on NCI.

TODO:
- Add YAML linting to product definitions (optional)
- Change Explorer to have built-in products and datasets

In picture form, the proposed directory structure is this:

image

### CODE REVIEW

**Comment by jeremyh** [comment]
Commented on the dea pr: https://github.com/GeoscienceAustralia/digitalearthau/pull/271#issuecomment-698102921

The dea repo uses and tests its products, so we'll want some migration of those parts. Unless we do the migration in the opposite direction.

**Comment by kieranricardo** [comment]
@alexgleith I fixed some of the yaml files here. Now I think once this is merged CI should pass for https://github.com/GeoscienceAustralia/digitalearthau/pull/271.

What else needs to be done before this can be merged?

**Comment by omad** [comment]
There have been some product changes in `digitalearthau` that need to be added to this PR before merging.

We also need to add any of the linting checks that are running over there to this repo, but I'm happy for that to happen either inside this PR, or in a new PR after this one has landed.

**Comment by jeremyh** [comment]
What do people think about adding an example dataset document for each product too?  (perhaps not in this PR)

Under the new structure, there could be an “examples” folder in each product folder, similar to the Stac repository.

Short-term, this would be nice for reference. Its currently hard to see whether any added product definitions are written correctly without tracking down where they are used.

Longer-term, I’d love to add `eo3-validate` linter to this repo so that we could validate that each product matches their example dataset (the set of measurements etc). The DEA repo does run `eo3-validate`, but only on product docs alone, which is less useful than the combination of the two.

**Comment by omad** [comment]
@jeremyh Awesome suggestions, but create a new issue please :)

**Comment by kieranricardo** [comment]
Here's a list of products missing in this PR compared to `develop` branch `digitalearthau`: 

```
['digitalearthau/digitalearthau/config/eo3/eo3.odc-type.yaml', 'digitalearthau/digitalearthau/config/eo3/products/ard_ls7.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls7.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/ard_ls8.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls8.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls7_ga.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls5_ga.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls8_c2.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls5.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls7_c2.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/ard_ls5.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products/l1_ls8_ga.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products-aws/ga_s2_wo_3.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products-aws/s2_ard_granule.yaml', 'digitalearthau/digitalearthau/config/eo3/products-aws/ard_ls7.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products-aws/ard_ls8.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products-aws/ga_ls8c_nbart_gm_cyear_3.odc-product.yaml', 'digitalearthau/digitalearthau/config/eo3/products-aws/ard_ls5.odc-product.yaml']
```

**Comment by kieranricardo** [comment]
oh wait I think some of these are differently named files but are the same product

**Comment by kieranricardo** [comment]
revising the list above with proposed moves:

- [ ] `config/eo3/eo3.odc-type.yaml`  -> `config/collection-3/metadata-types/`

I think these ones are named as `ga_ls*_level1_3.odc-product.yaml` in `dea-config` already

- [ ] config/eo3/products/l1_ls7.odc-product.yaml
- [ ] config/eo3/products/l1_ls7_ga.odc-product.yaml
- [ ] config/eo3/products/l1_ls5_ga.odc-product.yaml
- [ ] config/eo3/products/l1_ls8_c2.odc-product.yaml
- [ ] config/eo3/products/l1_ls5.odc-product.yaml
- [ ] config/eo3/products/l1_ls7_c2.odc-product.yaml
- [ ] config/eo3/products/l1_ls8_ga.odc-product.yaml


- [ ] config/eo3/products-aws/ga_s2_wo_3.odc-product.yaml -> `config/collection-3/derivative/s2_wo_3/`
- [ ] config/eo3/products-aws/s2_ard_granule.yaml -> `config/collection-3/baseline/`
- [ ] config/eo3/products-aws/ga_ls8c_nbart_gm_cyear_3.odc-product.yaml -> `config/collection-3/derivative/ga_ls8c_nbart_gm_cyear_3/`

@alexgleith @omad I'm assuming that the `products` folder should correspond to the `collection-{n}-nci` folders, and `products-aws` to the `collection-{n}` folders - is that right?

And which of the products above are collection 2 vs collection 3?

**Pull request closed without merging**
