### PR TITLE
rename lccs cyear file

### PR DESCRIPTION
**Pull request by pindge**

### CODE REVIEW

**Comment by robbibt** [comment]
Looks great Pin. Should we rename  the entire folder to "landcover"? LCCS is the old name I think (ping @tebadi)

**Comment by tebadi** [comment]
> Looks great Pin. Should we rename the entire folder to "landcover"? LCCS is the old name I think (ping @tebadi)

Good Suggestion Robbie! We no longer refer to landcover as LCCS as you said.

**Comment by pindge** [comment]
@tebadi @robbibt commit pushed

**Review by robbibt — APPROVED** [review]
Thanks Pin!

**Pull request merged**
