### PR TITLE
Burnt area

### PR DESCRIPTION
**Pull request by erin-telfer**
editing legends and colour maps

### CODE REVIEW

**Review by pindge — APPROVED** [review]

**Comment by pindge** [comment]
```
self.parse_legend(legend_cfg)
  File "/env/lib/python3.8/site-packages/datacube_ows/styles/ramp.py", line 361, in parse_legend
    self.parse_legend_tick_labels(cfg)
  File "/env/lib/python3.8/site-packages/datacube_ows/styles/ramp.py", line 440, in parse_legend_tick_labels
    prefix = label_cfg.get("prefix", default_prefix)
AttributeError: 'str' object has no attribute 'get'
Error: Process completed with exit code 1.
```

**Comment by erin-telfer** [comment]
I will fix errors now

**Comment by erin-telfer** [comment]
I think I have fixed conflict issues

**Comment by erin-telfer** [comment]
I will start again

**Pull request closed without merging**
