### PR TITLE
Add GeoMAD product definitions for financial years.

### PR DESCRIPTION
**Pull request by tebadi**

### CODE REVIEW

**Review by jmettes — APPROVED** [review]

**Comment by tebadi** [comment]
> Looks good. One thing I'm not sure of is checking whether the scale factors are correct

@omad could you please check this?  These are the same in calendar years and financial years.

**Comment by omad** [comment]
@jmettes @tebadi I don't understand. These don't contain any scale factors?

**Comment by tebadi** [comment]
> @jmettes @tebadi I don't understand. These don't contain any scale factors?

I thought Jono was referring to resolution and tile size but he can clarify himself.

**Comment by jmettes** [comment]
Yes, tile size and resolution, in conjunction to discussions about how geomedian/odc-stats was oversampling. I checked, and I think it's correct.

**Pull request merged**
